### ISSUE TITLE
Help me please !)

### ISSUE THREAD

**Issue by nocustom** [kettari/tallanto-api#29]
you can tell me how it works, what  I need to do to make, that it work, or which of these main files

**Comment by bookmanyak** [comment]
I have the same request +1
if possible with examples please
best regards

**Comment by kettari** [comment]
Hello guys,

In order to make this API work, Tallanto should open your database in read-only mode for your script. API will work in read-only mode.

"Update" and "create" operations work using curl through UI, logging in and updating web forms :) Unfortunately this was tested only with old UI. Current new UI was not tested =(

Hope this will help you.
